-- ============================================================
-- VEL Aerospace
-- TABLE CREATION
-- Run this file in Oracle SQL*Plus.
-- ============================================================

SET SERVEROUTPUT ON;
SET PAGESIZE 100;
SET LINESIZE 160;

-- Delete old objects if they already exist.
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CHECK_LOG CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MAINTENANCE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SALES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE PURCHASES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE AIRCRAFT CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE SUPPLIERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEES CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(5) PRIMARY KEY,
    FULL_NAME VARCHAR2(80) NOT NULL,
    ROLE_NAME VARCHAR2(40) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(20),
    STATUS VARCHAR2(15)
        CHECK (STATUS IN ('ACTIVE','INACTIVE'))
);

CREATE TABLE CUSTOMERS (
    CUSTOMER_ID NUMBER(5) PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE,
    PHONE VARCHAR2(20),
    CITY VARCHAR2(50),
    CUSTOMER_TYPE VARCHAR2(20)
        CHECK (CUSTOMER_TYPE IN ('INDIVIDUAL','COMPANY','GOVERNMENT'))
);

CREATE TABLE SUPPLIERS (
    SUPPLIER_ID NUMBER(5) PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(100) NOT NULL,
    CONTACT_PERSON VARCHAR2(80),
    EMAIL VARCHAR2(100),
    PHONE VARCHAR2(20),
    CITY VARCHAR2(50)
);

CREATE TABLE AIRCRAFT (
    AIRCRAFT_ID NUMBER(5) PRIMARY KEY,
    REGISTRATION_NO VARCHAR2(20) UNIQUE NOT NULL,
    MODEL_NAME VARCHAR2(60) NOT NULL,
    MANUFACTURER VARCHAR2(60) NOT NULL,
    AIRCRAFT_TYPE VARCHAR2(30) NOT NULL,
    MANUFACTURE_YEAR NUMBER(4),
    PURCHASE_PRICE NUMBER(14,2) CHECK (PURCHASE_PRICE >= 0),
    SELLING_PRICE NUMBER(14,2) CHECK (SELLING_PRICE >= 0),
    STATUS VARCHAR2(20)
        CHECK (STATUS IN ('AVAILABLE','SOLD','MAINTENANCE','RESERVED')),
    SUPPLIER_ID NUMBER(5),
    FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS(SUPPLIER_ID)
);

CREATE TABLE PURCHASES (
    PURCHASE_ID NUMBER(5) PRIMARY KEY,
    AIRCRAFT_ID NUMBER(5) NOT NULL,
    SUPPLIER_ID NUMBER(5) NOT NULL,
    PURCHASE_DATE DATE,
    AMOUNT NUMBER(14,2) CHECK (AMOUNT > 0),
    PAYMENT_STATUS VARCHAR2(20)
        CHECK (PAYMENT_STATUS IN ('PENDING','PAID','PARTIAL')),
    FOREIGN KEY (AIRCRAFT_ID)
        REFERENCES AIRCRAFT(AIRCRAFT_ID),
    FOREIGN KEY (SUPPLIER_ID)
        REFERENCES SUPPLIERS(SUPPLIER_ID)
);

CREATE TABLE SALES (
    SALE_ID NUMBER(5) PRIMARY KEY,
    AIRCRAFT_ID NUMBER(5) NOT NULL,
    CUSTOMER_ID NUMBER(5) NOT NULL,
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    SALE_DATE DATE,
    SALE_AMOUNT NUMBER(14,2) CHECK (SALE_AMOUNT > 0),
    PAYMENT_STATUS VARCHAR2(20)
        CHECK (PAYMENT_STATUS IN ('PENDING','PAID','PARTIAL')),
    FOREIGN KEY (AIRCRAFT_ID)
        REFERENCES AIRCRAFT(AIRCRAFT_ID),
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE MAINTENANCE (
    MAINTENANCE_ID NUMBER(5) PRIMARY KEY,
    AIRCRAFT_ID NUMBER(5) NOT NULL,
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    MAINTENANCE_DATE DATE,
    SERVICE_TYPE VARCHAR2(60),
    DESCRIPTION VARCHAR2(250),
    COST NUMBER(12,2) CHECK (COST >= 0),
    MAINTENANCE_STATUS VARCHAR2(20)
        CHECK (MAINTENANCE_STATUS IN ('OPEN','IN PROGRESS','COMPLETED')),
    FOREIGN KEY (AIRCRAFT_ID)
        REFERENCES AIRCRAFT(AIRCRAFT_ID),
    FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

CREATE TABLE CHECK_LOG (
    CHECK_ID NUMBER(6) PRIMARY KEY,
    CUSTOMER_ID NUMBER(5) NOT NULL,
    EMPLOYEE_ID NUMBER(5) NOT NULL,
    CHECK_IN_TIME TIMESTAMP,
    CHECK_OUT_TIME TIMESTAMP,
    PURPOSE VARCHAR2(100),
    STATUS VARCHAR2(10)
        CHECK (STATUS IN ('IN','OUT')),
    FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMERS(CUSTOMER_ID),
    FOREIGN KEY (EMPLOYEE_ID)
        REFERENCES EMPLOYEES(EMPLOYEE_ID)
);

COMMIT;

PROMPT VEL Aerospace tables created.
