-- ============================================================
-- VIEWS
-- ============================================================

CREATE OR REPLACE VIEW V_AIRCRAFT_DETAILS AS
SELECT
    A.AIRCRAFT_ID,
    A.REGISTRATION_NO,
    A.MODEL_NAME,
    A.MANUFACTURER,
    A.AIRCRAFT_TYPE,
    A.MANUFACTURE_YEAR,
    A.PURCHASE_PRICE,
    A.SELLING_PRICE,
    A.STATUS,
    S.SUPPLIER_NAME
FROM AIRCRAFT A
LEFT JOIN SUPPLIERS S
ON A.SUPPLIER_ID = S.SUPPLIER_ID;

CREATE OR REPLACE VIEW V_SALES_DETAILS AS
SELECT
    S.SALE_ID,
    A.REGISTRATION_NO,
    A.MODEL_NAME,
    C.CUSTOMER_NAME,
    E.FULL_NAME AS EMPLOYEE_NAME,
    S.SALE_DATE,
    S.SALE_AMOUNT,
    S.PAYMENT_STATUS
FROM SALES S
JOIN AIRCRAFT A
ON S.AIRCRAFT_ID = A.AIRCRAFT_ID
JOIN CUSTOMERS C
ON S.CUSTOMER_ID = C.CUSTOMER_ID
JOIN EMPLOYEES E
ON S.EMPLOYEE_ID = E.EMPLOYEE_ID;

CREATE OR REPLACE VIEW V_MAINTENANCE_DETAILS AS
SELECT
    M.MAINTENANCE_ID,
    A.REGISTRATION_NO,
    A.MODEL_NAME,
    M.SERVICE_TYPE,
    M.DESCRIPTION,
    M.MAINTENANCE_DATE,
    M.COST,
    M.MAINTENANCE_STATUS,
    E.FULL_NAME AS ENGINEER
FROM MAINTENANCE M
JOIN AIRCRAFT A
ON M.AIRCRAFT_ID = A.AIRCRAFT_ID
JOIN EMPLOYEES E
ON M.EMPLOYEE_ID = E.EMPLOYEE_ID;

COMMIT;

PROMPT Views created.
