-- ============================================================
-- BEGINNER SQL*PLUS QUERY PRACTICE
-- ============================================================

SET PAGESIZE 50;
SET LINESIZE 160;

PROMPT 1. Display all aircraft
SELECT * FROM AIRCRAFT;

PROMPT 2. Available aircraft
SELECT REGISTRATION_NO, MODEL_NAME, SELLING_PRICE
FROM AIRCRAFT
WHERE STATUS = 'AVAILABLE';

PROMPT 3. Aircraft with supplier using INNER/LEFT JOIN
SELECT
    A.REGISTRATION_NO,
    A.MODEL_NAME,
    S.SUPPLIER_NAME
FROM AIRCRAFT A
LEFT JOIN SUPPLIERS S
ON A.SUPPLIER_ID = S.SUPPLIER_ID;

PROMPT 4. Sales details using multiple joins
SELECT * FROM V_SALES_DETAILS;

PROMPT 5. Aggregate functions
SELECT
    COUNT(*) AS TOTAL_AIRCRAFT,
    MIN(SELLING_PRICE) AS MIN_PRICE,
    MAX(SELLING_PRICE) AS MAX_PRICE,
    ROUND(AVG(SELLING_PRICE),2) AS AVG_PRICE,
    SUM(SELLING_PRICE) AS TOTAL_VALUE
FROM AIRCRAFT;

PROMPT 6. GROUP BY
SELECT STATUS, COUNT(*) AS TOTAL
FROM AIRCRAFT
GROUP BY STATUS;

PROMPT 7. HAVING
SELECT SUPPLIER_ID, COUNT(*) AS TOTAL_AIRCRAFT
FROM AIRCRAFT
GROUP BY SUPPLIER_ID
HAVING COUNT(*) >= 1;

PROMPT 8. Subquery: aircraft above average price
SELECT REGISTRATION_NO, MODEL_NAME, SELLING_PRICE
FROM AIRCRAFT
WHERE SELLING_PRICE >
      (SELECT AVG(SELLING_PRICE) FROM AIRCRAFT);

PROMPT 9. IN clause
SELECT CUSTOMER_NAME, CITY
FROM CUSTOMERS
WHERE CITY IN ('Mumbai','Delhi');

PROMPT 10. BETWEEN clause
SELECT REGISTRATION_NO, MODEL_NAME, MANUFACTURE_YEAR
FROM AIRCRAFT
WHERE MANUFACTURE_YEAR BETWEEN 2020 AND 2024;

PROMPT 11. String functions
SELECT
    UPPER(MODEL_NAME) AS MODEL_UPPER,
    LOWER(MANUFACTURER) AS MANUFACTURER_LOWER,
    LENGTH(MODEL_NAME) AS MODEL_LENGTH
FROM AIRCRAFT;

PROMPT 12. Date function
SELECT
    SALE_ID,
    TO_CHAR(SALE_DATE,'DD-MON-YYYY') AS SALE_DATE
FROM SALES;

PROMPT 13. Check-in and check-out
SELECT
    C.CUSTOMER_NAME,
    L.CHECK_IN_TIME,
    L.CHECK_OUT_TIME,
    L.PURPOSE,
    L.STATUS
FROM CHECK_LOG L
JOIN CUSTOMERS C
ON L.CUSTOMER_ID = C.CUSTOMER_ID;

PROMPT 14. EXISTS example
SELECT CUSTOMER_NAME
FROM CUSTOMERS C
WHERE EXISTS (
    SELECT 1
    FROM CHECK_LOG L
    WHERE L.CUSTOMER_ID = C.CUSTOMER_ID
);

PROMPT 15. View
SELECT * FROM V_AIRCRAFT_DETAILS;
